

export const CALCULATE_BISHOP = "CALCULATE_BISHOP";
export const PARTURIENTS_LOADING = "PARTURIENTS_LOADING";
export const PARTURIENTS_FAILED = "PARTURIENTS_FAILED";
export const ADD_PARTURIENT = "ADD_PARTURIENT";
export const ADD_PARTURIENTS = "ADD_PARTURIENTS";
export const BISHOPS_FAILED = "BISHOPS_FAILED";
export const BISHOP_LOADING = "BISHOP_LOADING";
export const ADD_BISHOPS = "ADD_BISHOPS"



 