

export const CALCULATE_BISHOP = "CALCULATE_BISHOP";
export const PARTURIENTS_LOADING = "PARTURIENTS_LOADING";
export const PARTURIENTS_FAILED = "PARTURIENTS_FAILED";
export const ADD_PARTURIENT = "ADD_PARTURIENT";
export const ADD_PARTURIENTS = "ADD_PARTURIENTS";
export const BISHOPS_FAILED = "BISHOPS_FAILED";
export const BISHOP_LOADING = "BISHOP_LOADING";
export const ADD_BISHOPS = "ADD_BISHOPS"
export const ADD_USERS = "ADD_USERS";
export const USERS_FAILED = "USERS_FAILED";
export const ADD_USER = "ADD_USER";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const SIGNUP_REQUEST = "SIGNUP_REQUEST"
export const SIGNUP_FAILURE = "SIGNUP_FAILURE"




 