

export const CALCULATE_BISHOP = "CALCULATE_BISHOP";
export const PARTURIENTS_LOADING = "PARTURIENTS_LOADING";
export const PARTURIENTS_FAILED = "PARTURIENTS_FAILED";
export const ADD_PARTURIENTS = "ADD_PARTURIENTS";